controller_list:
  - name: fake_robot_controller
    joints:
      - iiwa_joint_1
      - iiwa_joint_2
      - iiwa_joint_3
      - iiwa_joint_4
      - iiwa_joint_5
      - iiwa_joint_6
      - iiwa_joint_7
  - name: fake_gripper_controller
    joints:
      - palm_finger_1_joint
      - finger_1_joint_1
      - palm_finger_2_joint
      - finger_2_joint_1
      - palm_finger_middle_joint
      - finger_middle_joint_1